// <auto-generated />
using System;
using AP190139Desafio1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP190139Desafio1.Migrations
{
    [DbContext(typeof(EmpleadosDBContext))]
    partial class EmpleadosDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP190139Desafio1.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly>("FechaDeNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("SueldoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Aguilar Panameño",
                            Cargo = "Programador",
                            Direccion = "Apopa,Col. 2, Psj.6, Casa #2",
                            FechaDeNacimiento = new DateOnly(2000, 7, 6),
                            Nombres = "David Alexander",
                            SueldoBase = 1200m,
                            Telefono = "72226082"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Perez Guerrero",
                            Cargo = "Vendedor",
                            Direccion = "Nejapa,Col. 11, Psj.1, Casa #32",
                            FechaDeNacimiento = new DateOnly(1992, 2, 1),
                            Nombres = "Pedro Felipe",
                            SueldoBase = 550m,
                            Telefono = "71710021"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Reyes Flores",
                            Cargo = "Vendedor",
                            Direccion = "Aguilares,Col. 2, Psj.4, Casa #12",
                            FechaDeNacimiento = new DateOnly(1990, 5, 9),
                            Nombres = "Sandra Alejandra",
                            SueldoBase = 550m,
                            Telefono = "76663625"
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Díaz Figueroa",
                            Cargo = "Contador",
                            Direccion = "Guazapa,Col. 31, Psj.29, Casa #1",
                            FechaDeNacimiento = new DateOnly(1993, 12, 8),
                            Nombres = "Juan Pablo",
                            SueldoBase = 650m,
                            Telefono = "74545466"
                        },
                        new
                        {
                            Id = 5,
                            Apellidos = "Aguilar Cortez",
                            Cargo = "Vendedor",
                            Direccion = "Soyapango,Col. 45, Psj.20, Casa #32",
                            FechaDeNacimiento = new DateOnly(1999, 4, 2),
                            Nombres = "Mariela Alexandra",
                            SueldoBase = 575m,
                            Telefono = "70212325"
                        },
                        new
                        {
                            Id = 6,
                            Apellidos = "Lopez Tobar",
                            Cargo = "Supervisor",
                            Direccion = "San Marcos,Col. 11, Psj.49, Casa #11",
                            FechaDeNacimiento = new DateOnly(2001, 12, 12),
                            Nombres = "Roberto Rodrigo",
                            SueldoBase = 600m,
                            Telefono = "76663636"
                        },
                        new
                        {
                            Id = 7,
                            Apellidos = "Flores Aguilar",
                            Cargo = "Programador",
                            Direccion = "Panchimalco,Col. 28, Psj.21, Casa #7",
                            FechaDeNacimiento = new DateOnly(1996, 2, 12),
                            Nombres = "Brenda Alejandra",
                            SueldoBase = 1000m,
                            Telefono = "78785525"
                        },
                        new
                        {
                            Id = 8,
                            Apellidos = "Melara Argueta",
                            Cargo = "Contador",
                            Direccion = "Apopa,Col. 17, Psj.17, Casa #8",
                            FechaDeNacimiento = new DateOnly(1998, 10, 12),
                            Nombres = "Juan David",
                            SueldoBase = 625m,
                            Telefono = "73636399"
                        },
                        new
                        {
                            Id = 9,
                            Apellidos = "Huezo Perez",
                            Cargo = "Bodeguero",
                            Direccion = "Soyapango,Col. 29, Psj.23, Casa #63",
                            FechaDeNacimiento = new DateOnly(1992, 8, 11),
                            Nombres = "Ricardo Mauricio",
                            SueldoBase = 500m,
                            Telefono = "70121589"
                        },
                        new
                        {
                            Id = 10,
                            Apellidos = "Ayala Pineda",
                            Cargo = "Bodeguero",
                            Direccion = "Nejapa,Col. 39, Psj.36, Casa #13",
                            FechaDeNacimiento = new DateOnly(1995, 1, 15),
                            Nombres = "Karla Lisset",
                            SueldoBase = 525m,
                            Telefono = "71477701"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
